In [1]:
# Install numpy
# Ya esta previamente instalada, por lo que no es necesario
#pip install numpy

In [2]:
# Colocar alias e importarlo al trabajo
import numpy as np

In [12]:
# Matriz por los 2 corchetes
arr=np.array([[1,2,3]])
print(arr.shape)
# 1 filas, 3 columnas

(1, 3)


In [13]:
print(arr)

[[1 2 3]]


In [11]:
# Una sola lista, es definido como vector, solo lleva unos corchetes
arr=np.array([1,2,3])
print(arr.shape)

# 3 elementos

(3,)


In [14]:
# Funciones basicas

# Creacion de arreglo
arr=np.array([1,2,3])

In [15]:
# Creacion de arreglo con ceros
zeros=np.zeros(3)
print(zeros)

[0. 0. 0.]


In [17]:
# Creacion de arreglo con unos
ones=np.ones(3)
print(ones)

[1. 1. 1.]


In [20]:
# Creacion de matriz con ceros
zerosMatrix=np.zeros((1024,3))
print(zerosMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# Creacion de matriz con unos
onesMatrix=np.ones((1024,3))
print(onesMatrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# Empty
# Valores aleatorios muy pequenios
# Creacion de matriz con empty
randomis=np.empty((1024,3))
print(randomis)

[[6.70343415e-310 6.70343415e-310 5.03904849e-310]
 [5.03904849e-310 6.70338470e-310 5.03904849e-310]
 [6.70338470e-310 5.03904854e-310 6.70338470e-310]
 ...
 [6.70339182e-310 6.70339182e-310 6.70339182e-310]
 [6.70343389e-310 6.70339183e-310 6.70343389e-310]
 [6.70339182e-310 6.70339182e-310 6.70343389e-310]]


In [24]:
# array en arange
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# array en arange con parametros
# Inicia en 0, menor al 20, con aumento de 3
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [28]:
# linspace
# Create an array that are spaced linearly in an interval.
arr=np.linspace(0,15,num=2)
print(arr)

[ 0. 15.]


In [31]:
# ordenar un arreglo
arr=np.array([4,2,5,6,3,2,4,2,7,8,9,4,3,3])
np.sort(arr)

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 6, 7, 8, 9])